name: Build and release
on: 
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
          python setup.py sdist
      - name: Show resources
        run: | 
          ls -l dist
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          release_name: ${{ steps.get_version.outputs.version }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/${{ github.event.repository.name }}-${{ steps.get_version.outputs.version-without-v }}.tar.gz
          asset_name: ${{ github.event.repository.name }}-${{ steps.get_version.outputs.version }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          body: ${{ steps.tag.outputs.message }}